[package]
name = "thunderlord"
version = "0.1.0"
authors = ["Adrian Martinez <adrianjustinmartinez@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.31.0", features = ["bundled", "static-link"] }